version: 2
updates:
 - package-ecosystem: gradle
   directory: "/"
   schedule:
     interval: daily
     time: "15:00"
     timezone: "Europe/Warsaw"
  - package-ecosystem: "npm"
    directory: "/chat-formatter-site"
    schedule:
     interval: daily
     time: "15:00"
     timezone: "Europe/Warsaw"
