name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Gradle
        uses: actions/cache@v3.3.2
        with:
          path: ~/.gradle/caches
          key: >-
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: '${{ runner.os }}-gradle-'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@62cce3c597efd445cd71ee868887b8b1117703a7
        with:
          arguments: core:shadowJar paper-support:shadowJar
      - name: Upload a ChatFormatter Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: 'Successfully build ChatFormatter'
          path: core/build/libs/*.jar
      - name: Upload a PaperSupport Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: 'Successfully build PaperSupport'
          path: paper-support/build/libs/*.jar
