name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Gradle
        uses: actions/cache@v4.2.2
        with:
          path: ~/.gradle/caches
          key: >-
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: '${{ runner.os }}-gradle-'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff
        with:
          arguments: shadowAll
      - name: Upload a ChatFormatter Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: 'Successfully build ChatFormatter'
          path: build/libs/ChatFormatter v*.jar