name: Build and Deploy docs
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        TARGET_REPO: EternalCodeTeam/ChatFormatte
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm && npm run build
        BUILD_DIR: chat-formatter-site/src/.vuepress/dist
        CNAME: https://chatformatter.eternalcode.pl
